### ISSUE TITLE
ImportError: No module named 'gtk'

### ISSUE THREAD

**Issue by danmaz74** [salseeg/ping-indicator#15]
I downloaded and installed the .deb on Ubuntu 16.04 and executed from the command line:

> ping-indicator

Traceback (most recent call last):
  File "/usr/bin/ping-indicator", line 4, in <module>
    import gtk
ImportError: No module named 'gtk'

**Comment by salseeg** [comment]
hi I'll check dependency this weekend .. what is your platform 64bit or 32bit ?

**Comment by danmaz74** [comment]
64 bit - let me know if I need to run any checks locally

**Comment by salseeg** [comment]
is this one installs well? https://salseeg.github.io/ping-indicator/download/ping-indicator_1.0-3_amd64.deb

**Comment by danmaz74** [comment]
unfortunately, same problem

**Comment by salseeg** [comment]
I would need a list of our packages installed then
Paste  result of following command here or on pastebin.com
`dpkg --get-selections `

**Comment by danmaz74** [comment]
There you go: http://pastebin.com/kyzXmy4U

**Comment by salseeg** [comment]
try to install python-gnome2

**Comment by danmaz74** [comment]
Nope... sudo apt-get install python-gnome2

...

Setting up python-gnome2 (2.28.1+dfsg-1.1) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
daniele@daniele-ubuntu:~$ ping-indicator
Traceback (most recent call last):
  File "/usr/bin/ping-indicator", line 4, in <module>
    import gtk
ImportError: No module named 'gtk'

**Comment by salseeg** [comment]
will try to reproduce ... but this needs some time

**Comment by danmaz74** [comment]
Yes of course, thanks for your work!

**Comment by salseeg** [comment]
Please run these in terminal
`env python --version`
`env python -v >out.txt`

**Comment by danmaz74** [comment]
Ok, found it:

daniele@daniele-ubuntu:~$ python --version
Python 3.3.6
daniele@daniele-ubuntu:~$ python3 --version
Python 3.3.6
daniele@daniele-ubuntu:~$ python2 --version
Python 2.7.12

I had installed pyenv for some project (I usually don't program in Python)
and the default was 3. Didn't remember that.

$ pyenv versions
  system
* 3.3.6 (set by /home/daniele/.pyenv/version)

After doing

$ pyenv global system

it works. I don't know if it would make sense for you to default to
"python2" as the interpreter if available...

Thanks for your support!

By the way, and OT question: is it possible to set a threshold for packet
loss to have a colored bar? That's actually what I was most interested into.

**Comment by salseeg** [comment]
Glad to hear it works for you!!!

I'm not sure if I got you right ... Do you want to be able to set loss threshold?  or when it gets red?

You may play with
https://github.com/salseeg/ping-indicator/blob/master/src/indicator/python/ping-indicator-daemon.py#L37

but unsure it is  the only place

**Comment by danmaz74** [comment]
Actually what I was thinking was having a rolling average for packet losses so that you could see the % in the last (say) 1 minute, and set a threshold for an alert color. But it's already useful like this, thanks!
