### ISSUE TITLE
please add 32bit deb download

### ISSUE THREAD

**Issue by hotice** [salseeg/ping-indicator#6]
Only a 64bit deb is offered for download. Please consider adding a 32bit deb as well.

_Deleted initial bug report, I see there's also a daemon wrapper that's arch-specific, so it can be built for all architectures._

**Comment by salseeg** [comment]
Will do within a week or two

**Comment by salseeg** [comment]
@hotice, I've added i386 version, plz check it

**Comment by hotice** [comment]
Thank you!
